// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/message_code_desc.proto

package xx.love.cc.message;

public final class MessageCodeDesc {
  private MessageCodeDesc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(xx.love.cc.message.MessageCodeDesc.messageCode);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int MESSAGE_CODE_FIELD_NUMBER = 1000;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      xx.love.cc.message.MessageCode> messageCode = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        xx.love.cc.message.MessageCode.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%message/proto/message_code_desc.proto\032" +
      " google/protobuf/descriptor.proto*a\n\013Mes" +
      "sageCode\022\022\n\016SYS_HEART_BEAT\020\000\022\016\n\tCG_TEST_" +
      "1\020\351\007\022\016\n\tGC_TEST_1\020\352\007\022\016\n\tCG_TEST_2\020\315\010\022\016\n\t" +
      "GC_TEST_2\020\316\010:D\n\014message_code\022\037.google.pr" +
      "otobuf.MessageOptions\030\350\007 \001(\0162\014.MessageCo" +
      "deB\030\n\022xx.love.cc.messageH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    messageCode.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
