// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/base_message_desc.proto

package xx.love.cc.message.base;

public interface BaseProtobufMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BaseProtobufMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 协议号
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * 业务protobuf转成的byte数据
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 业务protobuf转成的byte数据
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
