// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/base_message_desc.proto

package xx.love.cc.message.base;

public final class BaseMessageDesc {
  private BaseMessageDesc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseProtobufMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseProtobufMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CGTest1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CGTest1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GCTest1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GCTest1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%message/proto/base_message_desc.proto\032" +
      "%message/proto/message_code_desc.proto\"4" +
      "\n\023BaseProtobufMessage\022\014\n\004code\030\001 \001(\005\022\017\n\007c" +
      "ontent\030\002 \001(\t\"\035\n\007CGTest1\022\014\n\004text\030\001 \001(\t:\004\300" +
      ">\351\007\"\034\n\007GCTest1\022\013\n\003age\030\001 \001(\005:\004\300>\352\007B\035\n\027xx." +
      "love.cc.message.baseH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xx.love.cc.message.MessageCodeDesc.getDescriptor(),
        });
    internal_static_BaseProtobufMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseProtobufMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseProtobufMessage_descriptor,
        new java.lang.String[] { "Code", "Content", });
    internal_static_CGTest1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CGTest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CGTest1_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_GCTest1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GCTest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GCTest1_descriptor,
        new java.lang.String[] { "Age", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(xx.love.cc.message.MessageCodeDesc.messageCode);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    xx.love.cc.message.MessageCodeDesc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
