// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/base_message_desc.proto

package xx.love.cc.message.base;

public interface CGTest1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:CGTest1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
