// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/base_message_desc.proto

package xx.love.cc.message.base;

public interface GCTest1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:GCTest1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
