// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/hello_message_desc.proto

package xx.love.cc.message.hello;

public interface CGTest2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:CGTest2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test2 = 1;</code>
   * @return The test2.
   */
  java.lang.String getTest2();
  /**
   * <code>string test2 = 1;</code>
   * @return The bytes for test2.
   */
  com.google.protobuf.ByteString
      getTest2Bytes();
}
