// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/hello_message_desc.proto

package xx.love.cc.message.hello;

public interface GCTest2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:GCTest2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
