// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_message_desc.proto

package xx.love.cc.message.hello;

public interface HelloProtobufMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloProtobufMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 text = 3;</code>
   * @return The text.
   */
  int getText();
}
