// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/proto/hello_message_desc.proto

package xx.love.cc.message.hello;

public final class HelloMessageDesc {
  private HelloMessageDesc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CGTest2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CGTest2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GCTest2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GCTest2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&message/proto/hello_message_desc.proto" +
      "\032%message/proto/message_code_desc.proto\"" +
      "\036\n\007CGTest2\022\r\n\005test2\030\001 \001(\t:\004\300>\315\010\"\034\n\007GCTes" +
      "t2\022\013\n\003age\030\001 \001(\005:\004\300>\316\010B\036\n\030xx.love.cc.mess" +
      "age.helloH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xx.love.cc.message.MessageCodeDesc.getDescriptor(),
        });
    internal_static_CGTest2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CGTest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CGTest2_descriptor,
        new java.lang.String[] { "Test2", });
    internal_static_GCTest2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GCTest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GCTest2_descriptor,
        new java.lang.String[] { "Age", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(xx.love.cc.message.MessageCodeDesc.messageCode);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    xx.love.cc.message.MessageCodeDesc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
